language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - pypy

before_install: pip install simplejson

before_script: easy_install distribute
  
script: python setup.py test

branches:
  except:
    - website
